vaccines:
  - owid_name: "Moderna"
    org_name:
      - "MOD"
      - "MODBA.1"
      - "MODBA.4-5"
      - "MODBIV"
  - owid_name: "Pfizer/BioNTech"
    org_name:
      - "COM"
      - "COMBA.1"
      - "COMBA.4-5"
      - "COMBIV"
  - owid_name: "Oxford/AstraZeneca"
    org_name: "AZ"
  - owid_name: "Johnson&Johnson"
    org_name: "JANSS"
  - owid_name: "Sanofi/GSK"
    org_name: "SGSK"
  - owid_name: "Sputnik V"
    org_name: "SPU"
  - owid_name: "Sinopharm/Beijing"
    org_name: "BECNBG"
  - owid_name: "Novavax"
    org_name: "NVXD"
  - owid_name: "Novavax"
    org_name: "NVX"
  - owid_name: "Covaxin"
    org_name: "BHACOV"
  - owid_name: "Sinovac"
    org_name: "SIN"
  - owid_name: "Valneva"
    org_name: "VLA"
